% === RULES ===
% 어떤 사례(Case)가 어떤 패턴(Pattern)을 따르고, 그 패턴이 어떤 법(Law)을 위반하는지 추론
violates(Case, Pattern, Law) :-
    case_predicate(Case, Predicate),
    predicate_type(Predicate, Pattern),
    type_law(Pattern, Law).

% === facts ===

predicate_type(inconsistent_pricing_display, comparison_prevention).
predicate_type(hidden_plan_details, comparison_prevention).
predicate_type(complex_feature_bundling, comparison_prevention).
predicate_type(detect_confirmshaming_phrase, confirmshaming).
predicate_type(check_opt_out_label, confirmshaming).
predicate_type(analyze_emotional_trigger, confirmshaming).
predicate_type(is_disguised_ad_element, disguised_ads).
predicate_type(has_similar_appearance_to_content, disguised_ads).
predicate_type(confuses_user_with_ad_placement, disguised_ads).
predicate_type(detect_fake_low_stock_message, fake_scarcity).
predicate_type(analyze_fake_high_demand_indicators, fake_scarcity).
predicate_type(verify_artificial_scarcity_settings, fake_scarcity).
predicate_type(detect_fake_testimonials, fake_social_proof).
predicate_type(check_activity_message_legitimacy, fake_social_proof).
predicate_type(validate_social_proof_data, fake_social_proof).
predicate_type(detect_fake_countdown_timer, fake_urgency).
predicate_type(identify_repeated_urgency_phrases, fake_urgency).
predicate_type(check_urgency_message_visibility, fake_urgency).
predicate_type(forced_action_detected, forced_action).
predicate_type(visual_interference_present, forced_action).
predicate_type(bundled_consent_detected, forced_action).
predicate_type(hidden_cancellation_option, hard_to_cancel).
predicate_type(requires_customer_service_call, hard_to_cancel).
predicate_type(complex_cancellation_process, hard_to_cancel).
predicate_type(delayed_cost_reveal, hidden_costs).
predicate_type(initial_low_price_advertisement, hidden_costs).
predicate_type(lengthy_process_before_cost_reveal, hidden_costs).
predicate_type(hidden_subscription_triggered_by_action, hidden_subscription).
predicate_type(recurring_payment_without_notification, hidden_subscription).
predicate_type(subscription_details_not_disclosed, hidden_subscription).
predicate_type(repeated_interruptions, nagging).
predicate_type(lack_of_permanent_dismissal_option, nagging).
predicate_type(attention_depletion_metric, nagging).
predicate_type(obstruction_detected, obstruction).
predicate_type(confusing_navigation_path, obstruction).
predicate_type(disproportionate_effort_required, obstruction).
predicate_type(preselected_checkbox, preselection).
predicate_type(preselected_cart_items, preselection).
predicate_type(preselected_step_options, preselection).
predicate_type(sneaking_hidden_costs, sneaking).
predicate_type(sneaking_unwanted_items, sneaking).
predicate_type(sneaking_obscured_information, sneaking).
predicate_type(ambiguous_instruction, trick_wording).
predicate_type(misleading_dropdown_option, trick_wording).
predicate_type(scan_reading_exploit, trick_wording).
predicate_type(low_contrast_text, visual_interference).
predicate_type(chaotic_interface, visual_interference).
predicate_type(unexpected_information_placement, visual_interference).

type_law(obstruction, arizona_consumer_fraud_act_ars_s_44-1521).
type_law(sneaking, arizona_consumer_fraud_act_ars_s_44-1521).
type_law(visual_interference, arizona_consumer_fraud_act_ars_s_44-1521).
type_law(forced_action, arizona_consumer_fraud_act_ars_s_44-1521).
type_law(trick_wording, austria_data_protection_act_(dsg)_-_section_24_(6)).
type_law(fake_social_proof, can-spam_act_-_section_5(a)(1)_&_15_usc_s_7704(a)(1)).
type_law(hidden_subscription, california_consumers_legal_remedies_act_cal_civ_code_s_1750).
type_law(hard_to_cancel, california_consumers_legal_remedies_act_cal_civ_code_s_1750).
type_law(hidden_subscription, california’s_false_advertising_law_cal_bus_&_prof_code_s_17500).
type_law(hard_to_cancel, california’s_false_advertising_law_cal_bus_&_prof_code_s_17500).
type_law(hard_to_cancel, children’s_online_privacy_protection_act_rule).
type_law(forced_action, children’s_online_privacy_protection_act_rule).
type_law(obstruction, children’s_online_privacy_protection_act_rule).
type_law(forced_action, codice_privacy_-_article_130).
type_law(hard_to_cancel, codice_privacy_-_article_130).
type_law(sneaking, codice_privacy_-_article_130).
type_law(fake_urgency, consumer_contracts_(information_cancellation_and_additional_charges)_regulations_2013).
type_law(fake_scarcity, consumer_contracts_(information_cancellation_and_additional_charges)_regulations_2013).
type_law(fake_social_proof, consumer_contracts_(information_cancellation_and_additional_charges)_regulations_2013).
type_law(hidden_costs, consumer_contracts_(information_cancellation_and_additional_charges)_regulations_2013).
type_law(hidden_subscription, consumer_contracts_(information_cancellation_and_additional_charges)_regulations_2013).
type_law(hard_to_cancel, consumer_contracts_(information_cancellation_and_additional_charges)_regulations_2013).
type_law(hidden_subscription, consumer_financial_protection_act).
type_law(forced_action, consumer_financial_protection_act).
type_law(hard_to_cancel, consumer_financial_protection_act).
type_law(sneaking, consumer_fraud_act_new_jersey_stat_ann_s_56:8-2).
type_law(hidden_costs, consumer_protection_cooperation_(cpc)_regulation_(2006/2004/ec)).
type_law(fake_urgency, consumer_protection_from_unfair_trading_regulations_2008).
type_law(fake_scarcity, consumer_protection_from_unfair_trading_regulations_2008).
type_law(fake_social_proof, consumer_protection_from_unfair_trading_regulations_2008).
type_law(hidden_costs, consumer_protection_from_unfair_trading_regulations_2008).
type_law(hidden_subscription, consumer_protection_from_unfair_trading_regulations_2008).
type_law(hard_to_cancel, consumer_protection_from_unfair_trading_regulations_2008).
type_law(sneaking, consumer_protection_from_unfair_trading_regulations_2008).
type_law(fake_urgency, consumer_rights_act_2015).
type_law(fake_scarcity, consumer_rights_act_2015).
type_law(fake_social_proof, consumer_rights_act_2015).
type_law(hidden_costs, consumer_rights_act_2015).
type_law(hidden_subscription, consumer_rights_act_2015).
type_law(hard_to_cancel, consumer_rights_act_2015).
type_law(forced_action, consumer_rights_act_2015).
type_law(sneaking, consumer_rights_act_2015).
type_law(preselection, directive_95/46_-_article_2(h)).
type_law(preselection, directive_95/46_-_article_6).
type_law(preselection, directive_95/46_-_article_7).
type_law(hidden_costs, district’s_consumer_protection_procedures_act_s_28-3904).
type_law(forced_action, district’s_consumer_protection_procedures_act_s_28-3904).
type_law(sneaking, district’s_consumer_protection_procedures_act_s_28-3904).
type_law(hidden_costs, dutch_civil_code_(unfair_commercial_practices)_-_section_633a).
type_law(preselection, dutch_civil_code_(unfair_commercial_practices)_-_section_633a).
type_law(trick_wording, dutch_policy_rules_administrative_fines_2019).
type_law(fake_urgency, electronic_commerce_(ec_directive)_regulations_2002).
type_law(fake_scarcity, electronic_commerce_(ec_directive)_regulations_2002).
type_law(fake_social_proof, electronic_commerce_(ec_directive)_regulations_2002).
type_law(hidden_costs, electronic_commerce_(ec_directive)_regulations_2002).
type_law(forced_action, electronic_fund_transfer_act_(efta)).
type_law(hard_to_cancel, electronic_fund_transfer_act_(efta)).
type_law(hidden_subscription, electronic_fund_transfer_act_(efta)).
type_law(hidden_costs, fair_credit_reporting_act_-_15_usc_ss1681-1681).
type_law(hard_to_cancel, fair_credit_reporting_act_-_15_usc_ss1681-1681).
type_law(trick_wording, federal_constitution_(austria)_-_article_8).
type_law(hidden_costs, federal_trade_commission_act_-_section_5(a)_15_usc_s_45(a)).
type_law(hard_to_cancel, federal_trade_commission_act_-_section_5(a)_15_usc_s_45(a)).
type_law(hidden_subscription, federal_trade_commission_act_-_section_5(a)_15_usc_s_45(a)).
type_law(sneaking, federal_trade_commission_act_-_section_5(a)_15_usc_s_45(a)).
type_law(trick_wording, federal_trade_commission_act_-_section_5(a)_15_usc_s_45(a)).
type_law(fake_social_proof, federal_trade_commission_act_-_section_5(a)_15_usc_s_45(a)).
type_law(forced_action, federal_trade_commission_act_-_section_5(a)_15_usc_s_45(a)).
type_law(visual_interference, federal_trade_commission_act_-_section_5(a)_15_usc_s_45(a)).
type_law(obstruction, federal_trade_commission_act_-_section_5(a)_15_usc_s_45(a)).
type_law(confirmshaming, federal_trade_commission_act_-_section_5(a)_15_usc_s_45(a)).
type_law(forced_action, french_data_protection_act_-_article_82).
type_law(hard_to_cancel, french_data_protection_act_-_article_82).
type_law(visual_interference, french_data_protection_act_-_article_82).
type_law(obstruction, french_data_protection_act_-_article_82).
type_law(sneaking, french_data_protection_act_-_article_82).
type_law(preselection, french_data_protection_act_-_article_82).
type_law(trick_wording, gdpr_-_article_03).
type_law(sneaking, gdpr_-_article_04(11)).
type_law(preselection, gdpr_-_article_04(11)).
type_law(forced_action, gdpr_-_article_04(11)).
type_law(hard_to_cancel, gdpr_-_article_04(11)).
type_law(visual_interference, gdpr_-_article_04(11)).
type_law(obstruction, gdpr_-_article_04(11)).
type_law(nagging, gdpr_-_article_04(11)).
type_law(disguised_ads, gdpr_-_article_04(11)).
type_law(trick_wording, gdpr_-_article_04(11)).
type_law(trick_wording, gdpr_-_article_04(16)).
type_law(preselection, gdpr_-_article_05).
type_law(forced_action, gdpr_-_article_05).
type_law(hard_to_cancel, gdpr_-_article_05).
type_law(visual_interference, gdpr_-_article_05).
type_law(obstruction, gdpr_-_article_05).
type_law(disguised_ads, gdpr_-_article_05).
type_law(sneaking, gdpr_-_article_05).
type_law(trick_wording, gdpr_-_article_05).
type_law(preselection, gdpr_-_article_06).
type_law(forced_action, gdpr_-_article_06).
type_law(hard_to_cancel, gdpr_-_article_06).
type_law(visual_interference, gdpr_-_article_06).
type_law(obstruction, gdpr_-_article_06).
type_law(disguised_ads, gdpr_-_article_06).
type_law(sneaking, gdpr_-_article_06).
type_law(nagging, gdpr_-_article_06).
type_law(trick_wording, gdpr_-_article_06).
type_law(preselection, gdpr_-_article_07).
type_law(forced_action, gdpr_-_article_07).
type_law(hard_to_cancel, gdpr_-_article_07).
type_law(obstruction, gdpr_-_article_07).
type_law(sneaking, gdpr_-_article_07).
type_law(trick_wording, gdpr_-_article_07).
type_law(visual_interference, gdpr_-_article_07).
type_law(sneaking, gdpr_-_article_08).
type_law(forced_action, gdpr_-_article_09).
type_law(sneaking, gdpr_-_article_12).
type_law(preselection, gdpr_-_article_12).
type_law(forced_action, gdpr_-_article_12).
type_law(hard_to_cancel, gdpr_-_article_12).
type_law(obstruction, gdpr_-_article_12).
type_law(trick_wording, gdpr_-_article_12).
type_law(visual_interference, gdpr_-_article_12).
type_law(nagging, gdpr_-_article_12).
type_law(preselection, gdpr_-_article_13).
type_law(forced_action, gdpr_-_article_13).
type_law(hard_to_cancel, gdpr_-_article_13).
type_law(obstruction, gdpr_-_article_13).
type_law(trick_wording, gdpr_-_article_13).
type_law(visual_interference, gdpr_-_article_13).
type_law(sneaking, gdpr_-_article_13).
type_law(nagging, gdpr_-_article_13).
type_law(preselection, gdpr_-_article_14).
type_law(forced_action, gdpr_-_article_14).
type_law(hard_to_cancel, gdpr_-_article_14).
type_law(obstruction, gdpr_-_article_14).
type_law(trick_wording, gdpr_-_article_14).
type_law(visual_interference, gdpr_-_article_14).
type_law(sneaking, gdpr_-_article_14).
type_law(hard_to_cancel, gdpr_-_article_15).
type_law(trick_wording, gdpr_-_article_15).
type_law(preselection, gdpr_-_article_15).
type_law(sneaking, gdpr_-_article_15).
type_law(forced_action, gdpr_-_article_15).
type_law(hard_to_cancel, gdpr_-_article_17).
type_law(sneaking, gdpr_-_article_17).
type_law(forced_action, gdpr_-_article_17).
type_law(preselection, gdpr_-_article_21).
type_law(forced_action, gdpr_-_article_21).
type_law(hard_to_cancel, gdpr_-_article_21).
type_law(sneaking, gdpr_-_article_21).
type_law(nagging, gdpr_-_article_21).
type_law(preselection, gdpr_-_article_24).
type_law(forced_action, gdpr_-_article_24).
type_law(hard_to_cancel, gdpr_-_article_24).
type_law(sneaking, gdpr_-_article_24).
type_law(trick_wording, gdpr_-_article_24).
type_law(hard_to_cancel, gdpr_-_article_25).
type_law(preselection, gdpr_-_article_25).
type_law(sneaking, gdpr_-_article_25).
type_law(forced_action, gdpr_-_article_25).
type_law(trick_wording, gdpr_-_article_25).
type_law(visual_interference, gdpr_-_article_25).
type_law(forced_action, gdpr_-_article_28).
type_law(hard_to_cancel, gdpr_-_article_28).
type_law(sneaking, gdpr_-_article_28).
type_law(forced_action, gdpr_-_article_32).
type_law(hard_to_cancel, gdpr_-_article_32).
type_law(sneaking, gdpr_-_article_32).
type_law(nagging, gdpr_-_article_32).
type_law(hard_to_cancel, gdpr_-_article_33).
type_law(sneaking, gdpr_-_article_33).
type_law(trick_wording, gdpr_-_article_37).
type_law(sneaking, gdpr_-_article_37).
type_law(forced_action, gdpr_-_article_37).
type_law(trick_wording, gdpr_-_article_38).
type_law(sneaking, gdpr_-_article_38).
type_law(forced_action, gdpr_-_article_38).
type_law(trick_wording, gdpr_-_article_39).
type_law(nagging, gdpr_-_article_42).
type_law(hard_to_cancel, gdpr_-_article_42).
type_law(nagging, gdpr_-_article_43).
type_law(forced_action, gdpr_-_article_43).
type_law(trick_wording, gdpr_-_article_57).
type_law(trick_wording, gdpr_-_article_58).
type_law(forced_action, gdpr_-_article_58).
type_law(obstruction, gdpr_-_article_58).
type_law(sneaking, gdpr_-_article_58).
type_law(forced_action, gdpr_-_article_83).
type_law(hard_to_cancel, gdpr_-_article_83).
type_law(trick_wording, gdpr_-_article_83).
type_law(sneaking, gdpr_-_article_83).
type_law(sneaking, gdpr_-_recital_32).
type_law(preselection, gdpr_-_recital_32).
type_law(forced_action, gdpr_-_recital_32).
type_law(forced_action, german_competition_act_-_section_19a(2)).
type_law(preselection, german_competition_act_-_section_19a(2)).
type_law(hidden_costs, gramm_leach_bliley_act_act_-_section_501_15_usc_s_6801).
type_law(hidden_costs, gramm_leach_bliley_act_act_-_section_502_15_usc_s_6802).
type_law(hidden_costs, gramm_leach_bliley_act_act_-_section_503_15_usc_s_6803).
type_law(hidden_subscription, italian_consumer_code_-_article_20).
type_law(hard_to_cancel, italian_consumer_code_-_article_20).
type_law(hard_to_cancel, italian_consumer_code_-_article_21).
type_law(hidden_subscription, italian_consumer_code_-_article_21).
type_law(hard_to_cancel, italian_consumer_code_-_article_22).
type_law(hidden_subscription, italian_consumer_code_-_article_22).
type_law(hidden_subscription, italian_consumer_code_-_article_24).
type_law(hard_to_cancel, italian_consumer_code_-_article_24).
type_law(hidden_subscription, italian_consumer_code_-_article_25).
type_law(hard_to_cancel, italian_consumer_code_-_article_25).
type_law(hard_to_cancel, marketing_control_act_-_section_6_8_and_9).
type_law(hidden_subscription, new_york_consumer_fraud_statute_ny_gen_bus_law_s_349).
type_law(hard_to_cancel, new_york_consumer_fraud_statute_ny_gen_bus_law_s_349).
type_law(hidden_subscription, north_carolina_automatic_renewal_statute_ncgs_section_75-41(a)).
type_law(hidden_costs, privacy_rule_16_cfr_part_313_(recodified_at_12_cfr_s_1016)).
type_law(hard_to_cancel, privacy_and_electronic_communications_(ec_directive)_regulation_2003_-_regulation_2(1)).
type_law(forced_action, privacy_and_electronic_communications_(ec_directive)_regulation_2003_-_regulation_2(1)).
type_law(nagging, privacy_and_electronic_communications_(ec_directive)_regulation_2003_-_regulation_21).
type_law(forced_action, privacy_and_electronic_communications_(ec_directive)_regulation_2003_-_regulation_21).
type_law(nagging, privacy_and_electronic_communications_(ec_directive)_regulation_2003_-_regulation_22).
type_law(hard_to_cancel, privacy_and_electronic_communications_(ec_directive)_regulation_2003_-_regulation_22).
type_law(forced_action, privacy_and_electronic_communications_(ec_directive)_regulation_2003_-_regulation_22).
type_law(hard_to_cancel, rosca_-_section_4_15_usc_s_8401).
type_law(hidden_subscription, rosca_-_section_4_15_usc_s_8401).
type_law(hard_to_cancel, rosca_-_section_4_15_usc_s_8402).
type_law(hidden_subscription, rosca_-_section_4_15_usc_s_8402).
type_law(hard_to_cancel, rosca_-_section_4_15_usc_s_8403).
type_law(hidden_subscription, rosca_-_section_4_15_usc_s_8403).
type_law(fake_social_proof, rosca_-_section_4_15_usc_s_8403).
type_law(fake_urgency, rosca_-_section_4_15_usc_s_8403).
type_law(forced_action, rosca_-_section_4_15_usc_s_8403).
type_law(visual_interference, rosca_-_section_4_15_usc_s_8403).
type_law(confirmshaming, rosca_-_section_4_15_usc_s_8403).
type_law(obstruction, rosca_-_section_4_15_usc_s_8403).
type_law(sneaking, rosca_-_section_4_15_usc_s_8403).
type_law(hard_to_cancel, rosca_-_section_4_15_usc_s_8404).
type_law(hidden_subscription, rosca_-_section_4_15_usc_s_8404).
type_law(hidden_costs, rosca_-_section_4_15_usc_s_8404).
type_law(hard_to_cancel, rosca_-_section_4_15_usc_s_8405).
type_law(hidden_subscription, rosca_-_section_4_15_usc_s_8405).
type_law(preselection, romanian_data_protection_act_(law_no_677/2001)_-_article_32).
type_law(preselection, spanish_data_protection_law_(lopdgdd)_-_article_11).
type_law(forced_action, spanish_data_protection_law_(lopdgdd)_-_article_11).
type_law(preselection, spanish_data_protection_law_(lopdgdd)_-_article_6).
type_law(forced_action, spanish_data_protection_law_(lopdgdd)_-_article_6).
type_law(hard_to_cancel, spanish_law_on_information_society_services_-_article_21).
type_law(preselection, spanish_law_on_information_society_services_-_article_22).
type_law(forced_action, spanish_law_on_information_society_services_-_article_22).
type_law(trick_wording, spanish_law_on_information_society_services_-_article_22).
type_law(sneaking, spanish_law_on_information_society_services_-_article_22).
type_law(fake_urgency, uk_code_of_non-broadcast_advertising_sales_promotion_and_direct_marketing).
type_law(hidden_costs, unfair_commercial_practices_directive_-_article_5).
type_law(hidden_costs, unfair_commercial_practices_directive_-_article_6).
type_law(hidden_costs, unfair_commercial_practices_directive_-_article_7).
type_law(hidden_subscription, unfair_competition_law_cal_bus_&_prof_code_s_17200).
type_law(hard_to_cancel, unfair_competition_law_cal_bus_&_prof_code_s_17200).
type_law(forced_action, unfair_competition_law_cal_bus_&_prof_code_s_17200).
type_law(fake_urgency, unfair_competition_law_cal_bus_&_prof_code_s_17200).
type_law(fake_social_proof, unfair_terms_in_consumer_contracts_regulations_1999).
type_law(comparison_prevention, unfair_terms_in_consumer_contracts_regulations_1999).
type_law(sneaking, unfair_terms_in_consumer_contracts_regulations_1999).
type_law(hidden_subscription, unfair_terms_in_consumer_contracts_regulations_1999).
type_law(forced_action, washington_consumer_protection_act_-_wash_rev_code_ss_1986010).
type_law(fake_urgency, washington_consumer_protection_act_-_wash_rev_code_ss_1986010).
type_law(forced_action, eprivacy_directive_-_article_5(3)).
type_law(hard_to_cancel, eprivacy_directive_-_article_5(3)).
type_law(visual_interference, eprivacy_directive_-_article_5(3)).
type_law(obstruction, eprivacy_directive_-_article_5(3)).
type_law(sneaking, eprivacy_directive_-_article_5(3)).

case_predicate(bundeskartellamts_administrative_proceeding_against_google, preselected_checkbox).
case_predicate(bundeskartellamts_administrative_proceeding_against_google, preselected_cart_items).
case_predicate(bundeskartellamts_administrative_proceeding_against_google, preselected_step_options).
case_predicate(in_the_matter_of_tiktok_technology_limited, preselected_checkbox).
case_predicate(in_the_matter_of_tiktok_technology_limited, preselected_cart_items).
case_predicate(in_the_matter_of_tiktok_technology_limited, preselected_step_options).
case_predicate(ftc_v._amazon.com_inc., obstruction_detected).
case_predicate(ftc_v._amazon.com_inc., confusing_navigation_path).
case_predicate(ftc_v._amazon.com_inc., disproportionate_effort_required).
case_predicate(ftc_v._amazon.com_inc., sneaking_hidden_costs).
case_predicate(ftc_v._amazon.com_inc., sneaking_unwanted_items).
case_predicate(ftc_v._amazon.com_inc., sneaking_obscured_information).
case_predicate(ftc_v._amazon.com_inc., detect_confirmshaming_phrase).
case_predicate(ftc_v._amazon.com_inc., check_opt_out_label).
case_predicate(ftc_v._amazon.com_inc., analyze_emotional_trigger).
case_predicate(in_the_matter_of_homeadvisor_inc., sneaking_hidden_costs).
case_predicate(in_the_matter_of_homeadvisor_inc., sneaking_unwanted_items).
case_predicate(in_the_matter_of_homeadvisor_inc., sneaking_obscured_information).
case_predicate(in_the_matter_of_epic_games_inc, obstruction_detected).
case_predicate(in_the_matter_of_epic_games_inc, confusing_navigation_path).
case_predicate(in_the_matter_of_epic_games_inc, disproportionate_effort_required).
case_predicate(deliberation_of_the_restricted_committee_concerning_apple_distribution_international, preselected_checkbox).
case_predicate(deliberation_of_the_restricted_committee_concerning_apple_distribution_international, preselected_cart_items).
case_predicate(deliberation_of_the_restricted_committee_concerning_apple_distribution_international, preselected_step_options).
case_predicate(deliberation_of_the_restricted_committee_concerning_apple_distribution_international, obstruction_detected).
case_predicate(deliberation_of_the_restricted_committee_concerning_apple_distribution_international, confusing_navigation_path).
case_predicate(deliberation_of_the_restricted_committee_concerning_apple_distribution_international, disproportionate_effort_required).
case_predicate(deliberation_of_the_restricted_formation_san-2022-027_concerning_tiktok, sneaking_hidden_costs).
case_predicate(deliberation_of_the_restricted_formation_san-2022-027_concerning_tiktok, sneaking_unwanted_items).
case_predicate(deliberation_of_the_restricted_formation_san-2022-027_concerning_tiktok, sneaking_obscured_information).
case_predicate(deliberation_of_the_restricted_committee_concerning_microsoft_ireland_operations_limited, sneaking_hidden_costs).
case_predicate(deliberation_of_the_restricted_committee_concerning_microsoft_ireland_operations_limited, sneaking_unwanted_items).
case_predicate(deliberation_of_the_restricted_committee_concerning_microsoft_ireland_operations_limited, sneaking_obscured_information).
case_predicate(deliberation_of_the_restricted_committee_concerning_microsoft_ireland_operations_limited, obstruction_detected).
case_predicate(deliberation_of_the_restricted_committee_concerning_microsoft_ireland_operations_limited, confusing_navigation_path).
case_predicate(deliberation_of_the_restricted_committee_concerning_microsoft_ireland_operations_limited, disproportionate_effort_required).
case_predicate(irelands_data_protection_commission_investigation_into_yahoo, obstruction_detected).
case_predicate(irelands_data_protection_commission_investigation_into_yahoo, confusing_navigation_path).
case_predicate(irelands_data_protection_commission_investigation_into_yahoo, disproportionate_effort_required).
case_predicate(federal_trade_commission_v._vonage_holdings_corporation, sneaking_hidden_costs).
case_predicate(federal_trade_commission_v._vonage_holdings_corporation, sneaking_unwanted_items).
case_predicate(federal_trade_commission_v._vonage_holdings_corporation, sneaking_obscured_information).
case_predicate(jp/politikens_hus_a/s_investigation_by_danish_dpa, obstruction_detected).
case_predicate(jp/politikens_hus_a/s_investigation_by_danish_dpa, confusing_navigation_path).
case_predicate(jp/politikens_hus_a/s_investigation_by_danish_dpa, disproportionate_effort_required).
case_predicate(jp/politikens_hus_a/s_investigation_by_danish_dpa, sneaking_hidden_costs).
case_predicate(jp/politikens_hus_a/s_investigation_by_danish_dpa, sneaking_unwanted_items).
case_predicate(jp/politikens_hus_a/s_investigation_by_danish_dpa, sneaking_obscured_information).
case_predicate(ms_xx_(complainant)_v._douglas_italia_s.p.a., sneaking_hidden_costs).
case_predicate(ms_xx_(complainant)_v._douglas_italia_s.p.a., sneaking_unwanted_items).
case_predicate(ms_xx_(complainant)_v._douglas_italia_s.p.a., sneaking_obscured_information).
case_predicate(state_of_arizona_ex_rel._mark_brnovich_attorney_general_v._google_llc, obstruction_detected).
case_predicate(state_of_arizona_ex_rel._mark_brnovich_attorney_general_v._google_llc, confusing_navigation_path).
case_predicate(state_of_arizona_ex_rel._mark_brnovich_attorney_general_v._google_llc, disproportionate_effort_required).
case_predicate(state_of_arizona_ex_rel._mark_brnovich_attorney_general_v._google_llc, sneaking_hidden_costs).
case_predicate(state_of_arizona_ex_rel._mark_brnovich_attorney_general_v._google_llc, sneaking_unwanted_items).
case_predicate(state_of_arizona_ex_rel._mark_brnovich_attorney_general_v._google_llc, sneaking_obscured_information).
case_predicate(meta_platforms_ireland_limited_and_instagram_social_media_networks_investigation_by_dpc, preselected_checkbox).
case_predicate(meta_platforms_ireland_limited_and_instagram_social_media_networks_investigation_by_dpc, preselected_cart_items).
case_predicate(meta_platforms_ireland_limited_and_instagram_social_media_networks_investigation_by_dpc, preselected_step_options).
case_predicate(meta_platforms_ireland_limited_and_instagram_social_media_networks_investigation_by_dpc, sneaking_hidden_costs).
case_predicate(meta_platforms_ireland_limited_and_instagram_social_media_networks_investigation_by_dpc, sneaking_unwanted_items).
case_predicate(meta_platforms_ireland_limited_and_instagram_social_media_networks_investigation_by_dpc, sneaking_obscured_information).
case_predicate(d.a.a.a_(data_subjects)_v._infotv, sneaking_hidden_costs).
case_predicate(d.a.a.a_(data_subjects)_v._infotv, sneaking_unwanted_items).
case_predicate(d.a.a.a_(data_subjects)_v._infotv, sneaking_obscured_information).
case_predicate(la_quadrature_du_net_v._amazon_europe_core, sneaking_hidden_costs).
case_predicate(la_quadrature_du_net_v._amazon_europe_core, sneaking_unwanted_items).
case_predicate(la_quadrature_du_net_v._amazon_europe_core, sneaking_obscured_information).
case_predicate(executive-committee_of_the_belgian_dpa_(gba)_v._rossel_&_cie, preselected_checkbox).
case_predicate(executive-committee_of_the_belgian_dpa_(gba)_v._rossel_&_cie, preselected_cart_items).
case_predicate(executive-committee_of_the_belgian_dpa_(gba)_v._rossel_&_cie, preselected_step_options).
case_predicate(executive-committee_of_the_belgian_dpa_(gba)_v._rossel_&_cie, obstruction_detected).
case_predicate(executive-committee_of_the_belgian_dpa_(gba)_v._rossel_&_cie, confusing_navigation_path).
case_predicate(executive-committee_of_the_belgian_dpa_(gba)_v._rossel_&_cie, disproportionate_effort_required).
case_predicate(executive-committee_of_the_belgian_dpa_(gba)_v._rossel_&_cie, sneaking_hidden_costs).
case_predicate(executive-committee_of_the_belgian_dpa_(gba)_v._rossel_&_cie, sneaking_unwanted_items).
case_predicate(executive-committee_of_the_belgian_dpa_(gba)_v._rossel_&_cie, sneaking_obscured_information).
case_predicate(executive-committee_of_the_belgian_dpa_(gba)_v._roularta_media_group, preselected_checkbox).
case_predicate(executive-committee_of_the_belgian_dpa_(gba)_v._roularta_media_group, preselected_cart_items).
case_predicate(executive-committee_of_the_belgian_dpa_(gba)_v._roularta_media_group, preselected_step_options).
case_predicate(executive-committee_of_the_belgian_dpa_(gba)_v._roularta_media_group, sneaking_hidden_costs).
case_predicate(executive-committee_of_the_belgian_dpa_(gba)_v._roularta_media_group, sneaking_unwanted_items).
case_predicate(executive-committee_of_the_belgian_dpa_(gba)_v._roularta_media_group, sneaking_obscured_information).
case_predicate(mr._b.b.b_(data_subject)_v._ms._a.a.a_(owner_of_commercial_website), sneaking_hidden_costs).
case_predicate(mr._b.b.b_(data_subject)_v._ms._a.a.a_(owner_of_commercial_website), sneaking_unwanted_items).
case_predicate(mr._b.b.b_(data_subject)_v._ms._a.a.a_(owner_of_commercial_website), sneaking_obscured_information).
case_predicate(mrs._a.a.a._(lias_clothing)_and_zulmar_santamaria_s.l., sneaking_hidden_costs).
case_predicate(mrs._a.a.a._(lias_clothing)_and_zulmar_santamaria_s.l., sneaking_unwanted_items).
case_predicate(mrs._a.a.a._(lias_clothing)_and_zulmar_santamaria_s.l., sneaking_obscured_information).
case_predicate(organization_of_consumers_and_users_v._my_heritage_ltd, sneaking_hidden_costs).
case_predicate(organization_of_consumers_and_users_v._my_heritage_ltd, sneaking_unwanted_items).
case_predicate(organization_of_consumers_and_users_v._my_heritage_ltd, sneaking_obscured_information).
case_predicate(ramona_films_s.l._investigation_by_spanish_agency_for_the_protection_of_data, sneaking_hidden_costs).
case_predicate(ramona_films_s.l._investigation_by_spanish_agency_for_the_protection_of_data, sneaking_unwanted_items).
case_predicate(ramona_films_s.l._investigation_by_spanish_agency_for_the_protection_of_data, sneaking_obscured_information).
case_predicate(deliberation_of_the_restricted_committee_concerning_facebook_ireland_limited, obstruction_detected).
case_predicate(deliberation_of_the_restricted_committee_concerning_facebook_ireland_limited, confusing_navigation_path).
case_predicate(deliberation_of_the_restricted_committee_concerning_facebook_ireland_limited, disproportionate_effort_required).
case_predicate(deliberation_of_the_restricted_committee_concerning_facebook_ireland_limited, sneaking_hidden_costs).
case_predicate(deliberation_of_the_restricted_committee_concerning_facebook_ireland_limited, sneaking_unwanted_items).
case_predicate(deliberation_of_the_restricted_committee_concerning_facebook_ireland_limited, sneaking_obscured_information).
case_predicate(deliberation_of_the_restricted_committee_concerning_google_llc_and_google_ireland_limited, obstruction_detected).
case_predicate(deliberation_of_the_restricted_committee_concerning_google_llc_and_google_ireland_limited, confusing_navigation_path).
case_predicate(deliberation_of_the_restricted_committee_concerning_google_llc_and_google_ireland_limited, disproportionate_effort_required).
case_predicate(d.a.a.a_(data_subject)_v._komplett_bank_asa, repeated_interruptions).
case_predicate(d.a.a.a_(data_subject)_v._komplett_bank_asa, lack_of_permanent_dismissal_option).
case_predicate(d.a.a.a_(data_subject)_v._komplett_bank_asa, attention_depletion_metric).
case_predicate(enforcement_action_by_ico_against_unite_the_union, repeated_interruptions).
case_predicate(enforcement_action_by_ico_against_unite_the_union, lack_of_permanent_dismissal_option).
case_predicate(enforcement_action_by_ico_against_unite_the_union, attention_depletion_metric).
case_predicate(d.a.a.a._(complainant)_v._preico_juridicos_s.l., sneaking_hidden_costs).
case_predicate(d.a.a.a._(complainant)_v._preico_juridicos_s.l., sneaking_unwanted_items).
case_predicate(d.a.a.a._(complainant)_v._preico_juridicos_s.l., sneaking_obscured_information).
case_predicate(we_buy_any_car_limited_investigation_by_information_commissioners_office, repeated_interruptions).
case_predicate(we_buy_any_car_limited_investigation_by_information_commissioners_office, lack_of_permanent_dismissal_option).
case_predicate(we_buy_any_car_limited_investigation_by_information_commissioners_office, attention_depletion_metric).
case_predicate(irelands_data_protection_commission_investigation_into_whatsapp_ireland_limited, obstruction_detected).
case_predicate(irelands_data_protection_commission_investigation_into_whatsapp_ireland_limited, confusing_navigation_path).
case_predicate(irelands_data_protection_commission_investigation_into_whatsapp_ireland_limited, disproportionate_effort_required).
case_predicate(irelands_data_protection_commission_investigation_into_whatsapp_ireland_limited, sneaking_hidden_costs).
case_predicate(irelands_data_protection_commission_investigation_into_whatsapp_ireland_limited, sneaking_unwanted_items).
case_predicate(irelands_data_protection_commission_investigation_into_whatsapp_ireland_limited, sneaking_obscured_information).
case_predicate(d.a.a.a_(complainant)_through_cnil_v._société_du_figaro, sneaking_hidden_costs).
case_predicate(d.a.a.a_(complainant)_through_cnil_v._société_du_figaro, sneaking_unwanted_items).
case_predicate(d.a.a.a_(complainant)_through_cnil_v._société_du_figaro, sneaking_obscured_information).
case_predicate(d.a.a.a_(complainant)_v._radio_popular_s.a., sneaking_hidden_costs).
case_predicate(d.a.a.a_(complainant)_v._radio_popular_s.a., sneaking_unwanted_items).
case_predicate(d.a.a.a_(complainant)_v._radio_popular_s.a., sneaking_obscured_information).
case_predicate(colour_car_sales_limiteds_investigation_by_uk_dpa, sneaking_hidden_costs).
case_predicate(colour_car_sales_limiteds_investigation_by_uk_dpa, sneaking_unwanted_items).
case_predicate(colour_car_sales_limiteds_investigation_by_uk_dpa, sneaking_obscured_information).
case_predicate(czech_dpas_investigation_into_anonymous_television_broadcaster, sneaking_hidden_costs).
case_predicate(czech_dpas_investigation_into_anonymous_television_broadcaster, sneaking_unwanted_items).
case_predicate(czech_dpas_investigation_into_anonymous_television_broadcaster, sneaking_obscured_information).
case_predicate(federal_trade_commission_v._age_of_learning_inc._(abcmouse), sneaking_hidden_costs).
case_predicate(federal_trade_commission_v._age_of_learning_inc._(abcmouse), sneaking_unwanted_items).
case_predicate(federal_trade_commission_v._age_of_learning_inc._(abcmouse), sneaking_obscured_information).
case_predicate(subdirectorate_general_for_data_inspection_v._flexografica_del_mediterraneo_s.l., sneaking_hidden_costs).
case_predicate(subdirectorate_general_for_data_inspection_v._flexografica_del_mediterraneo_s.l., sneaking_unwanted_items).
case_predicate(subdirectorate_general_for_data_inspection_v._flexografica_del_mediterraneo_s.l., sneaking_obscured_information).
case_predicate(d.a.a.a._v._abanca_corporacion_bancaria_s.a., sneaking_hidden_costs).
case_predicate(d.a.a.a._v._abanca_corporacion_bancaria_s.a., sneaking_unwanted_items).
case_predicate(d.a.a.a._v._abanca_corporacion_bancaria_s.a., sneaking_obscured_information).
case_predicate(d.a.a.a._&_ors_v._caixabank_s.a., preselected_checkbox).
case_predicate(d.a.a.a._&_ors_v._caixabank_s.a., preselected_cart_items).
case_predicate(d.a.a.a._&_ors_v._caixabank_s.a., preselected_step_options).
case_predicate(d.a.a.a_(claimant)_v._washpoint_s.l., sneaking_hidden_costs).
case_predicate(d.a.a.a_(claimant)_v._washpoint_s.l., sneaking_unwanted_items).
case_predicate(d.a.a.a_(claimant)_v._washpoint_s.l., sneaking_obscured_information).
case_predicate(anonymous_(complainant)_v._national_service_for_the_promotion_of_childcare_products, sneaking_hidden_costs).
case_predicate(anonymous_(complainant)_v._national_service_for_the_promotion_of_childcare_products, sneaking_unwanted_items).
case_predicate(anonymous_(complainant)_v._national_service_for_the_promotion_of_childcare_products, sneaking_obscured_information).
case_predicate(asociación_de_consumidores_y_usuarios_en_acción_(facua)_v._asociación_de_afectados_por_las_asociaciones_de_consumidores_(asocapac), sneaking_hidden_costs).
case_predicate(asociación_de_consumidores_y_usuarios_en_acción_(facua)_v._asociación_de_afectados_por_las_asociaciones_de_consumidores_(asocapac), sneaking_unwanted_items).
case_predicate(asociación_de_consumidores_y_usuarios_en_acción_(facua)_v._asociación_de_afectados_por_las_asociaciones_de_consumidores_(asocapac), sneaking_obscured_information).
case_predicate(d.aaa_(claimant)_v._banco_bilbao_vizcaya_argentaria_sa, preselected_checkbox).
case_predicate(d.aaa_(claimant)_v._banco_bilbao_vizcaya_argentaria_sa, preselected_cart_items).
case_predicate(d.aaa_(claimant)_v._banco_bilbao_vizcaya_argentaria_sa, preselected_step_options).
case_predicate(d.aaa_(claimant)_v._banco_bilbao_vizcaya_argentaria_sa, sneaking_hidden_costs).
case_predicate(d.aaa_(claimant)_v._banco_bilbao_vizcaya_argentaria_sa, sneaking_unwanted_items).
case_predicate(d.aaa_(claimant)_v._banco_bilbao_vizcaya_argentaria_sa, sneaking_obscured_information).
case_predicate(carrefour_france_investigation_by_cnil, sneaking_hidden_costs).
case_predicate(carrefour_france_investigation_by_cnil, sneaking_unwanted_items).
case_predicate(carrefour_france_investigation_by_cnil, sneaking_obscured_information).
case_predicate(mr_x_(the_complainant)_v._y_housing_company_(the_defendant), sneaking_hidden_costs).
case_predicate(mr_x_(the_complainant)_v._y_housing_company_(the_defendant), sneaking_unwanted_items).
case_predicate(mr_x_(the_complainant)_v._y_housing_company_(the_defendant), sneaking_obscured_information).
case_predicate(d.a.a.a._v._miguel_ibanez_bezanilla_s.l., sneaking_hidden_costs).
case_predicate(d.a.a.a._v._miguel_ibanez_bezanilla_s.l., sneaking_unwanted_items).
case_predicate(d.a.a.a._v._miguel_ibanez_bezanilla_s.l., sneaking_obscured_information).
case_predicate(d.a.a.a._(complainant)_v._iberia_lineas_aereas_de_espana_s.a._operadora_unipersonal, sneaking_hidden_costs).
case_predicate(d.a.a.a._(complainant)_v._iberia_lineas_aereas_de_espana_s.a._operadora_unipersonal, sneaking_unwanted_items).
case_predicate(d.a.a.a._(complainant)_v._iberia_lineas_aereas_de_espana_s.a._operadora_unipersonal, sneaking_obscured_information).
case_predicate(d.a.a.a_v._vueling_airlines_s.a., preselected_checkbox).
case_predicate(d.a.a.a_v._vueling_airlines_s.a., preselected_cart_items).
case_predicate(d.a.a.a_v._vueling_airlines_s.a., preselected_step_options).
case_predicate(d.a.a.a_(claimant)_on_behalf_of_neptunos_formación_s.l._v._iweb_internet_learning_s.l., sneaking_hidden_costs).
case_predicate(d.a.a.a_(claimant)_on_behalf_of_neptunos_formación_s.l._v._iweb_internet_learning_s.l., sneaking_unwanted_items).
case_predicate(d.a.a.a_(claimant)_on_behalf_of_neptunos_formación_s.l._v._iweb_internet_learning_s.l., sneaking_obscured_information).
case_predicate(d.a.a.a_(claimant)_v._eslora_proyectos_s.l., sneaking_hidden_costs).
case_predicate(d.a.a.a_(claimant)_v._eslora_proyectos_s.l., sneaking_unwanted_items).
case_predicate(d.a.a.a_(claimant)_v._eslora_proyectos_s.l., sneaking_obscured_information).
case_predicate(d.a.a.a._(complainant)_v._wind_tre_spa, sneaking_hidden_costs).
case_predicate(d.a.a.a._(complainant)_v._wind_tre_spa, sneaking_unwanted_items).
case_predicate(d.a.a.a._(complainant)_v._wind_tre_spa, sneaking_obscured_information).
case_predicate(den_blå_avis_ex_officio_investigation_by_danish_dpa, sneaking_hidden_costs).
case_predicate(den_blå_avis_ex_officio_investigation_by_danish_dpa, sneaking_unwanted_items).
case_predicate(den_blå_avis_ex_officio_investigation_by_danish_dpa, sneaking_obscured_information).
case_predicate(d.a.a.a._(claimant)_v._happy_friday_sl, sneaking_hidden_costs).
case_predicate(d.a.a.a._(claimant)_v._happy_friday_sl, sneaking_unwanted_items).
case_predicate(d.a.a.a._(claimant)_v._happy_friday_sl, sneaking_obscured_information).
case_predicate(inspection_by_gba_-_x_-_y_website, preselected_checkbox).
case_predicate(inspection_by_gba_-_x_-_y_website, preselected_cart_items).
case_predicate(inspection_by_gba_-_x_-_y_website, preselected_step_options).
case_predicate(inspection_by_gba_-_x_-_y_website, sneaking_hidden_costs).
case_predicate(inspection_by_gba_-_x_-_y_website, sneaking_unwanted_items).
case_predicate(inspection_by_gba_-_x_-_y_website, sneaking_obscured_information).
case_predicate(planet_49_vs_ecj, preselected_checkbox).
case_predicate(planet_49_vs_ecj, preselected_cart_items).
case_predicate(planet_49_vs_ecj, preselected_step_options).
case_predicate(planet_49_vs_ecj, sneaking_hidden_costs).
case_predicate(planet_49_vs_ecj, sneaking_unwanted_items).
case_predicate(planet_49_vs_ecj, sneaking_obscured_information).
case_predicate(d.a.a.a_(data_subject)_v._canary_click_consulting_website, sneaking_hidden_costs).
case_predicate(d.a.a.a_(data_subject)_v._canary_click_consulting_website, sneaking_unwanted_items).
case_predicate(d.a.a.a_(data_subject)_v._canary_click_consulting_website, sneaking_obscured_information).
case_predicate(ngo_la_quadrature_du_net_(lqdn)_and_noyb_(complainant)_v._google_llc, obstruction_detected).
case_predicate(ngo_la_quadrature_du_net_(lqdn)_and_noyb_(complainant)_v._google_llc, confusing_navigation_path).
case_predicate(ngo_la_quadrature_du_net_(lqdn)_and_noyb_(complainant)_v._google_llc, disproportionate_effort_required).
case_predicate(ngo_la_quadrature_du_net_(lqdn)_and_noyb_(complainant)_v._google_llc, preselected_checkbox).
case_predicate(ngo_la_quadrature_du_net_(lqdn)_and_noyb_(complainant)_v._google_llc, preselected_cart_items).
case_predicate(ngo_la_quadrature_du_net_(lqdn)_and_noyb_(complainant)_v._google_llc, preselected_step_options).
case_predicate(ngo_la_quadrature_du_net_(lqdn)_and_noyb_(complainant)_v._google_llc, sneaking_hidden_costs).
case_predicate(ngo_la_quadrature_du_net_(lqdn)_and_noyb_(complainant)_v._google_llc, sneaking_unwanted_items).
case_predicate(ngo_la_quadrature_du_net_(lqdn)_and_noyb_(complainant)_v._google_llc, sneaking_obscured_information).