% predicate ↔ case
predicate_case(inconsistent_pricing_display, case001).
predicate_case(hidden_plan_details, case001).
predicate_case(complex_feature_bundling, case001).
predicate_case(detect_confirmshaming_phrase, case002).
predicate_case(check_opt_out_label, case002).
predicate_case(analyze_emotional_trigger, case002).
predicate_case(is_disguised_ad_element, case003).
predicate_case(has_similar_appearance_to_content, case003).
predicate_case(confuses_user_with_ad_placement, case003).
predicate_case(detect_fake_low_stock_message, case004).
predicate_case(analyze_fake_high_demand_indicators, case004).
predicate_case(verify_artificial_scarcity_settings, case004).
predicate_case(detect_fake_testimonials, case005).
predicate_case(check_activity_message_legitimacy, case005).
predicate_case(validate_social_proof_data, case005).
predicate_case(detect_fake_countdown_timer, case006).
predicate_case(identify_repeated_urgency_phrases, case006).
predicate_case(check_urgency_message_visibility, case006).
predicate_case(forced_action_detected, case007).
predicate_case(visual_interference_present, case007).
predicate_case(bundled_consent_detected, case007).
predicate_case(hidden_cancellation_option, case008).
predicate_case(requires_customer_service_call, case008).
predicate_case(complex_cancellation_process, case008).
predicate_case(delayed_cost_reveal, case009).
predicate_case(initial_low_price_advertisement, case009).
predicate_case(lengthy_process_before_cost_reveal, case009).
predicate_case(hidden_subscription_triggered_by_action, case010).
predicate_case(recurring_payment_without_notification, case010).
predicate_case(subscription_details_not_disclosed, case010).
predicate_case(repeated_interruptions, case011).
predicate_case(lack_of_permanent_dismissal_option, case011).
predicate_case(attention_depletion_metric, case011).
predicate_case(obstruction_detected, case012).
predicate_case(confusing_navigation_path, case012).
predicate_case(disproportionate_effort_required, case012).
predicate_case(preselected_checkbox, case013).
predicate_case(preselected_cart_items, case013).
predicate_case(preselected_step_options, case013).
predicate_case(sneaking_hidden_costs, case014).
predicate_case(sneaking_unwanted_items, case014).
predicate_case(sneaking_obscured_information, case014).
predicate_case(ambiguous_instruction, case015).
predicate_case(misleading_dropdown_option, case015).
predicate_case(scan_reading_exploit, case015).
predicate_case(low_contrast_text, case016).
predicate_case(chaotic_interface, case016).
predicate_case(unexpected_information_placement, case016).