% predicate ↔ pattern
predicate_type(inconsistent_pricing_display, comparison_prevention).
predicate_type(hidden_plan_details, comparison_prevention).
predicate_type(complex_feature_bundling, comparison_prevention).
predicate_type(detect_confirmshaming_phrase, confirmshaming).
predicate_type(check_opt_out_label, confirmshaming).
predicate_type(analyze_emotional_trigger, confirmshaming).
predicate_type(is_disguised_ad_element, disguised_ads).
predicate_type(has_similar_appearance_to_content, disguised_ads).
predicate_type(confuses_user_with_ad_placement, disguised_ads).
predicate_type(detect_fake_low_stock_message, fake_scarcity).
predicate_type(analyze_fake_high_demand_indicators, fake_scarcity).
predicate_type(verify_artificial_scarcity_settings, fake_scarcity).
predicate_type(detect_fake_testimonials, fake_social_proof).
predicate_type(check_activity_message_legitimacy, fake_social_proof).
predicate_type(validate_social_proof_data, fake_social_proof).
predicate_type(detect_fake_countdown_timer, fake_urgency).
predicate_type(identify_repeated_urgency_phrases, fake_urgency).
predicate_type(check_urgency_message_visibility, fake_urgency).
predicate_type(forced_action_detected, forced_action).
predicate_type(visual_interference_present, forced_action).
predicate_type(bundled_consent_detected, forced_action).
predicate_type(hidden_cancellation_option, hard_to_cancel).
predicate_type(requires_customer_service_call, hard_to_cancel).
predicate_type(complex_cancellation_process, hard_to_cancel).
predicate_type(delayed_cost_reveal, hidden_costs).
predicate_type(initial_low_price_advertisement, hidden_costs).
predicate_type(lengthy_process_before_cost_reveal, hidden_costs).
predicate_type(hidden_subscription_triggered_by_action, hidden_subscription).
predicate_type(recurring_payment_without_notification, hidden_subscription).
predicate_type(subscription_details_not_disclosed, hidden_subscription).
predicate_type(repeated_interruptions, nagging).
predicate_type(lack_of_permanent_dismissal_option, nagging).
predicate_type(attention_depletion_metric, nagging).
predicate_type(obstruction_detected, obstruction).
predicate_type(confusing_navigation_path, obstruction).
predicate_type(disproportionate_effort_required, obstruction).
predicate_type(preselected_checkbox, preselection).
predicate_type(preselected_cart_items, preselection).
predicate_type(preselected_step_options, preselection).
predicate_type(sneaking_hidden_costs, sneaking).
predicate_type(sneaking_unwanted_items, sneaking).
predicate_type(sneaking_obscured_information, sneaking).
predicate_type(ambiguous_instruction, trick_wording).
predicate_type(misleading_dropdown_option, trick_wording).
predicate_type(scan_reading_exploit, trick_wording).
predicate_type(low_contrast_text, visual_interference).
predicate_type(chaotic_interface, visual_interference).
predicate_type(unexpected_information_placement, visual_interference).